spring:
  application:
    name: 01_MINI_Project_Counsellors_Portal
  datasource:
    url: jdbc:mysql://localhost:3306/jrtp28?createDatabaseIfNotExist=true
    username: root
    password: 757082
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:      
      ddl-auto: create
    show-sql: true
